[program:laravel-log]
command=/bin/sh -c "mkdir -p /var/www/html/storage/logs && touch /var/www/html/storage/logs/laravel.log && tail -F /var/www/html/storage/logs/laravel.log"
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
startretries=5
startsecs=1
