[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
redirect_stderr=true
# Stream nginx logs to container stdout/stderr
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
startretries=10
startsecs=3
