<x-layout>
    <div class="section">
        <h1 class="title">Reports</h1>
        <p class="lead">Export booking reports in your preferred format.</p>
    </div>

    <div class="card">
        <h2 class="subtitle">Booking Reports</h2>
        <div class="stack" style="margin-top: 2rem;">
            <div class="report-option">
                <div>
                    <strong>CSV Report</strong>
                    <p class="lead">Download as CSV format for spreadsheet applications.</p>
                </div>
                <a href="{{ route('admin.reports.bookings', ['format' => 'csv']) }}" class="btn btn-primary" download>
                    Download CSV
                </a>
            </div>

            <div class="report-option">
                <div>
                    <strong>XLSX Report</strong>
                    <p class="lead">Download as XLSX format (Excel spreadsheet).</p>
                </div>
                <a href="{{ route('admin.reports.bookings', ['format' => 'xlsx']) }}" class="btn btn-primary" download>
                    Download XLSX
                </a>
            </div>

            <div class="report-option">
                <div>
                    <strong>PDF Report</strong>
                    <p class="lead">Download as PDF format for printing and sharing.</p>
                </div>
                <a href="{{ route('admin.reports.bookings', ['format' => 'pdf']) }}" class="btn btn-primary" download>
                    Download PDF
                </a>
            </div>
        </div>
    </div>

    <div class="card mt-4">
        <h2 class="subtitle">Report History</h2>

        @if(isset($history) && $history->isNotEmpty())
            <div class="tablewrap" style="margin-top: 1rem;">
                <table class="table">
                    <thead>
                        <tr>
                            <th class="th">Generated</th>
                            <th class="th">Format</th>
                            <th class="th">Rows</th>
                            <th class="th">Revenue</th>
                            <th class="th">Generated By</th>
                            <th class="th">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($history as $report)
                            <tr>
                                <td class="td">{{ $report->created_at->format('M d, Y H:i') }}</td>
                                <td class="td text-uppercase">{{ $report->format }}</td>
                                <td class="td">{{ $report->row_count }}</td>
                                <td class="td">PHP {{ number_format($report->total_revenue, 2) }}</td>
                                <td class="td">{{ $report->generated_by ?? 'System' }}</td>
                                <td class="td">
                                    <a href="{{ route('admin.reports.history.download', $report) }}" class="btn btn-sm btn-outline-secondary">Download</a>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>

            <div class="package-pagination mt-3">{{ $history->links() }}</div>
        @else
            <p class="lead" style="margin-top: 1rem;">No report exports have been generated yet.</p>
        @endif
    </div>
</x-layout>
